[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "ontology_project"
version = "0.1.1"
description = "A package to convert CSV files into ontology TTL files and merge them"
authors = [{ name = "Priyanka Bharti", email = "priyanka.bharti@npl.co.uk" }]
license = { file = "LICENSE" }
readme = { file = "README.md", content-type = "text/markdown; charset=UTF-8" }
dependencies = [
    "rdflib>=6.2.0",
    "pandas>=1.3.0",
    "owlready2>=0.38",
    "tqdm>=4.64.0",
    "sentence-transformers>=2.2.0",
    "scikit-learn>=1.0.0"
]

[project.scripts]
convert_ec3 = "ontology_project.Ec3EpdCsv_to_Ec3Epd_onto1:main"
convert_tru = "ontology_project.TruCsv_to_Tru_onto2:main"
convert_mcp = "ontology_project.McpCsv_to_Mcp_onto3:main"
merge_ontologies = "ontology_project.merge_ontology:merge_ontologies"
run_ontology = "ontology_project.runner:main"

[tool.setuptools]
packages = ["ontology_project"]

[tool.setuptools.package-data]
ontology_project = ["README.md","config.json"]
