[build-system]
requires = ["setuptools>=45", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "pykitten"
version = "0.1.0"
description = "A versatile Python toolkit for various utilities"
readme = "README.md"
authors = [{ name = "Agra Bima Yuda", email = "agra.bima.ab@gmail.com" }]
license = { file = "LICENSE" }
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "License :: OSI Approved :: MIT License",
    "Programming Language :: Python :: 3",
    "Programming Language :: Python :: 3.7",
    "Programming Language :: Python :: 3.8",
    "Programming Language :: Python :: 3.9",
    "Programming Language :: Python :: 3.10",
]
keywords = ["tools", "utilities", "audio", "wav"]
requires-python = ">=3.7"

[project.urls]
Homepage = "https://github.com/grabim09/SnakeTools"
Repository = "https://github.com/grabim09/SnakeTools.git"
Documentation = "https://github.com/grabim09/SnakeTools#readme"