[project]
name = "images-py"
version = "0.1.0"
description = "Kenneth Lambert's image processing library (UNOFFICIAL)"
readme = "README.md"
maintainers = [
    { name = "Aero", email = "aerocyberdev@proton.me" } # Only for the package. The library is not mine.
]
requires-python = ">=3.13"
dependencies = []
license = "GPL-3.0-or-later"


[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[tool.hatch.build.targets.wheel]
packages = ["src/images.py"]
