[project]
name = "armcortnet"
version = "0.2.7"
description = "An automated deep learning pipeline for segmentation of the scapula, humerus, and their respective subregions in CT scans."
authors = [
    {name = "gspangenberg",email = "gspangen@uwo.ca"}
]
readme = "README.md"

[tool.poetry.dependencies]
python = ">=3.11"
armcrop = ">=0.7"
nnunetv2 = ">=2.5"
huggingface-hub = ">=0.25.1"

[tool.poetry]
packages = [{include = "armcortnet"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
