# 用于定义项目的构建系统配置。
[build-system]
# 指定构建系统工具的要求。使用 "hatchling" 作为构建系统工具。
requires = ["hatchling"] #setuptools
# 指定构建系统的后端实现。
build-backend = "hatchling.build" #setuptools.build_meta

# 项目相关的各种信息。
[project]
# 项目的名称。
name = "py_diff_pdf2"
# 项目的版本号。
version = "1.1.3"
# 作者信息列表，包含作者的姓名和电子邮件。
authors = [
    { name = "lwinhong", email = "80469181@qq.com" },
]
# 项目的描述。
description = "pdf文档比对"
# 项目的 README 文件的名称。
readme = "README.md"
# 许可证信息，包含许可证文件的名称。
license = { file = "LICENSE" }
# 项目所需的 Python 版本。
requires-python = ">=3.6"
# 项目的分类器，用于指定项目的分类标签。例如编程语言、许可证、操作系统等。
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]
# 项目的依赖列表，指定其他项目或库的依赖关系。
dependencies = [
]

[tool.setuptools.packages.find]
where = ["src"]  # ["."] by default
exclude = ['tests', '*.pdf']

[tool.setuptools.package-data]
py_diff_pdf2 = ["*.dll", "*.rst"]

[tool.setuptools]
include-package-data = true

# 项目的相关网址
[project.urls]
# 项目的主页网址。
Homepage = "https://github.com/lwinhong/py-diff-pdf"
Issues = "https://github.com/lwinhong/py-diff-pdf/issues"