[project]
name = "jorbit"
version = "0.1.5"
description = "Solar system orbit fitting and integration with JAX"
readme = "README.md"
authors = [
    { name = "Ben-Cassese", email = "b.c.cassese@columbia.edu" }
]
requires-python = ">=3.10"
dependencies = [
    "astropy>=6.1.6",
    "astroquery>=0.4.7",
    "chex>=0.1.88",
    "emcee>=3.1.6",
    "ipykernel>=6.29.5", # just for animate_region
    "jax>=0.4.35",
    "jplephem>=2.22",
    "matplotlib>=3.9.2", # just for animate_region
    "mpmath>=1.3.0",
    "pandas>=2.2.3",
    "polars>=1.22.0",
    "pyarrow>=19.0.0",
    "scipy>=1.14.1",
    "tqdm>=4.67.1",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[dependency-groups]
dev = [
    "black[jupyter]>=24.10.0",
    "myst-parser>=4.0.0",
    "nbsphinx>=0.9.5",
    "pre-commit>=4.0.1",
    "pytest-cov>=6.0.0",
    "pytest-xdist>=3.6.1",
    "pytest>=8.3.4",
    "sphinx-automodapi>=0.18.0",
    "sphinx-book-theme>=1.1.3",
    "sphinx>=8.1.3",
    "sphinxcontrib-video>=0.3.1",
    "tox>=4.23.2",
    "tox-gh-actions>=3.2.0",
    "tox-uv>=1.16.2",
    "rebound>=4.4.5",
    "reboundx>=4.4.0",
    "ruff>=0.9.2",
    "codespell>=2.4.1",
    "sphinx-autodoc-typehints>=3.0.1",
]

[tool.ruff.lint]
ignore = [
    "E402", # want to enable jax64 before importing anything that might run jax code on import
    "B008", # want to use things like Time("2024-01-01") as defaults
    "B006", # unsure of this one- right now using {} as default for acceleration_func_kwargs
    "RUF012", # annoying when using NamedTuples
]
extend-select = ["W", "I", "B", "D", "UP", "SIM", "RUF", "ANN"]
exclude = [
    "docs/*",
    "src/jorbit/mpchecker/ephem_generation/*",
]
pydocstyle.convention = "google"

[tool.codespell]
skip = "./docs/_build/*, **/*.ipynb, ./src/jorbit/data/observatory_codes.py"
