[tool.poetry]
name = "ns_nornir_table_inventory"
version = "0.0.1"
description = "nornir inventory plugin,support managing inventory by csv or excel file"
authors = ["nstamoul <nstamoul0@gmail.com>"]
license = "Apache-2.0"
readme = "readme.md"
homepage = "https://github.com/nstamoul/ns_nornir_table_inventory"
repository = "https://github.com/nstamoul/ns_nornir_table_inventory"
keywords = ["nornir", "table", "csv", "excel", "inventory"]
classifiers = [
  "License :: OSI Approved :: Apache Software License",
  "Programming Language :: Python :: 3",
  "Programming Language :: Python :: 3.6",
  "Programming Language :: Python :: 3.7",
  "Programming Language :: Python :: 3.8",
  "Topic :: System :: Networking",
]



[tool.poetry.plugins."nornir.plugins.inventory"]
"FlatDataInventory" = "ns_nornir_table_inventory.plugins.inventory.table:FlatDataInventory"
"CSVInventory" = "ns_nornir_table_inventory.plugins.inventory.table:CSVInventory"
"ExcelInventory" = "ns_nornir_table_inventory.plugins.inventory.table:ExcelInventory"




[tool.poetry.dependencies]
python = ">=3.7"
nornir = ">=3.0.0"
pandas = ">=1.2.0"

[tool.poetry.dev-dependencies]
pytest = "^5.2"

[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"
