[project]
name = "nonebot-plugin-latex"
version = "0.0.3"
description = "通过互联网公共服务渲染LaTeX公式"
authors = [{ name = "Eilles", email = "EillesWan@outlook.com" }]
dependencies = [
    "nonebot2",
    "httpx>=0.27.0,<0.28.0",
    "nonebot-adapter-onebot",
    "nonebot-plugin-alconna",
]
requires-python = ">=3.9,<4.0"
readme = "README.md"
license = { file = "LICENSE" }

[project.urls]
"Homepage" = "https://github.com/EillesWan/nonebot-plugin-latex"
"Bug Tracker" = "https://github.com/EillesWan/nonebot-plugin-latex/issues"
