[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "wnox"
version = "0.3.0"
authors = [{ name = "Ethan (Armin) Cardan", email = "armin.fire@gmail.com" }]
description = "A short description of your package"
readme = "README.md"
license = { file = "LICENSE" }
dependencies = ["slixmpp","bson"]
requires-python = ">=3.12"
classifiers = [
    "Programming Language :: Python :: 3",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent"
]


[project.urls]
homepage = "https://github.com/arminkardan/pywnox"

