[project]
name = "agentevals"
version = "0.0.1-rc.2"
license = {text = "MIT"}
description = "Open-source evaluators for LLM agents"
readme = "README.md"
requires-python = ">=3.11"
dependencies = [
    "openevals==0.0.1rc3"
]

[dependency-groups]
dev = [
    "langgraph>=0.2.73",
    "openai>=1.61.1",
    "pytest>=8.3.4",
    "pytest-asyncio>=0.25.3",
    "ruff>=0.9.5",
]

[tool.pytest.ini_options]
addopts = [
    "--import-mode=importlib",
]
pythonpath = [
  "."
]
