[project]
name = "laravel-oauth2"
version = "0.1.2"
description = ""
authors = [
    {name = "Douglas B",email = "douglas.barbosa@ciadeestagios.com.br"}
]
readme = "README.md"
requires-python = ">=3.10.5"
dependencies = [
    "social-auth-app-django<=5.4.1",
    "social-auth-core==4.5.4",
    "pytest==8.3.4",
    "requests>=2.32.0"
    
]

[tool.poetry]
packages = [{include = "laravel_oauth2", from = "src"}]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
