[project]
name = "win-alias"
version = "1.0.2"
authors = [{name = "EverythingPython"}]
license = {text = "MIT"}
readme = "README.md"
description = "A simple CLI tool to create Windows aliases."
requires-python = ">=3.11"
dependencies = [
    "click>=8.0.1",
    "charset-normalizer==3.4.1",
    "colorama==0.4.6",
    "docutils==0.21.2",
    "flit==3.10.1",
    "idna==3.10",
    "requests==2.32.3",
    "tomli-w==1.2.0",
    "urllib3==2.3.0"
]

[project.urls]
Homepage = "https://github.com/everythingpython/win-alias"
Issues = "https://github.com/everythingpython/win-alias/issues"

[project.scripts]
win-alias = "win_alias:cli"

[build-system]
requires = ["flit_core<4"]
build-backend = "flit_core.buildapi"
