[project]
name = "enclave-py-sdk"
version = "0.1.8"
description = ""
authors = [
    {name = "Sumer Malhotra",email = "sumer@enclave.money"}
]
readme = "README.md"
requires-python = ">=3.8"
dependencies = [
    "requests (>=2.32.3,<3.0.0)"
]


[build-system]
requires = ["poetry-core>=2.0.0,<3.0.0"]
build-backend = "poetry.core.masonry.api"
