[tool.poetry]
name = "seqkan"
version = "0.7.2"
description = "This paper proposes seqKAN, a KAN architecture for sequence processing."
authors = ["Tatiana Boura <tat.boura@gmail.com>"]
readme = "README.md"
packages = [ {include = "src"} ]

[tool.poetry.dependencies]
python = "^3.10"
pyyaml = "^6.0.2"
torch = "^2.6.0"
pandas = "^2.2.3"
matplotlib = "^3.10.0"
tqdm = "^4.67.1"
sympy = "^1.13.1"


[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
