[build-system]
requires = ["setuptools", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "numeration_system"
version = "0.2.6"
authors = [{name = "Lucas Maciel", email = "lalucasforte56@gmail.com"}]
description = "A non-professional library created to provide value conversion functions in the number system."
readme = "README.md"
license = {file = "LICENSE"}
requires-python = ">=3.7"

[project.urls]
"Homepage" = "https://github.com/luca-maciel/calculadora_sistema_numera-o"
