[build-system]
requires = ["setuptools>=61.0", "wheel"]
build-backend = "setuptools.build_meta"

[project]
name = "machina-sdk"
version = "0.2.0"
description = "Machina Sports API SDK"
readme = "README.md"
requires-python = "==3.11.*"
license = { text = "MIT" }
authors = [
    { name = "Fernando Bombassaro Martins", email = "fernando@machina.gg" },
]
classifiers = [
    "Programming Language :: Python :: 3.9",
    "License :: OSI Approved :: MIT License",
    "Operating System :: OS Independent",
]

dependencies = [
    "requests>=2.26.0,<3.0.0",
    "pydantic",
]

[tool.pdm]
[tool.pdm.dev-dependencies]
dev = [
    "python-semantic-release==9.20.0",
]

[tool.setuptools.packages]
find = { where = ["src"] }

[tool.pyright]
venvPath = "."
venv = "venv"
