[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"

[project]
name = "win-purge"
version = "0.0.0"
license = {file = "LICENSE.md"}
authors = [
  { name="James Parrott", email="james.parrott@proton.me" },
]
description = "Delete registry keys, registry value/ value_names, path entries, and often used installation directories based on a string search."
readme = "README.md"
requires-python = ">=3.9"
dependencies = ["send2trash",
               ]

classifiers = [
    "Programming Language :: Python :: 3",
    "Operating System :: Microsoft :: Windows",
    ]


[project.scripts]
win_purge = "win_purge.__main__:main" 

[project.urls]   
"Homepage" = "https://github.com/Hazardous-Area/win_purge"
"Bug Tracker" = "https://github.com/Hazardous-Area/win_purge/issues"
