[package]
name = "aerolattice"
description = "A blazingly fast aerodynamics package built for modern aerospace applications."
repository = "https://github.com/josephrhobbs/aerolattice.git"
version = "0.9.0"
edition = "2021"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html
[lib]
name = "aerolattice"
crate-type = ["cdylib"]

[dependencies]
pyo3 = "0.23.3"
