[tool.poetry]
name = "just-semantic-search-scholar"
version = "0.0.0"
description = "Semantic and hybrid search with scholar"
authors = ["Anton Kulaga <antonkulaga@gmail.com>"]
license = "Apache-2.0"
readme = "README.md"
keywords = ["python", "llm", "science", "review", "hybrid search", "semantic search"]
classifiers = [
    "Development Status :: 3 - Alpha",
    "Intended Audience :: Developers",
    "Programming Language :: Python :: 3.11",
    "Operating System :: Unix",
    "Operating System :: MacOS :: MacOS X",
    "Operating System :: Microsoft :: Windows",
]

packages = [
    { include = "just_semantic_search" },
]

[tool.poetry.dependencies]
python = ">=3.11,<3.15"
scholarly = ">=1.7.11"
triton = ">=2.0.0"
sentence-transformers = ">=2.2.2"
typer = ">=0.9.0"
rich = ">=13.9.4"
semanticscholar = ">=0.10.0"
huggingface-hub = ">=0.27.0"
polars = ">=1.20.0"
pyfunctional = ">=1.5.0"
just-semantic-search-meili = "*"
patito = ">=0.8.3"
seaborn = ">=0.13.2"

[build-system]
requires = ["poetry-core>=2.1.1", "poetry-dynamic-versioning>=1.0.0"]
build-backend = "poetry.core.masonry.api" 

[tool.poetry-dynamic-versioning]
enable = true
vcs = "git"
style = "semver"
pattern = "(?P<base>\\d+\\.\\d+\\.\\d+)"
format-jinja = "{{base}}"

[tool.poetry.group.dev.dependencies]
just-semantic-search-meili = { path = "../meili", develop = true }
