[tool.poetry]
name = "lab-control"
version = "0.8.1"
description = "Remote control lab instruments"
authors = ["Lorenz Kies <lorenz.kies@aei.mpg.de>"]
readme = "README.md"

[tool.poetry.dependencies]
python = "^3.11"
numpy = "*"
pandas = "*"
pyvisa = "*"
plotly = "*"
pyserial = "^3.5"
pyyaml = "^6.0.2"

[tool.poetry.group.dev.dependencies]
flake8 = "^7.1.1"
flake8-bugbear = "^24.8.19"
ipykernel = "^6.29.5"

[build-system]
requires = ["poetry-core"]
build-backend = "poetry.core.masonry.api"
